version: '3.9'
services:
  client:
    stdin_open: true
    tty: true
    container_name: reactjs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/client
      - /client/node_modules