version: '3.9'
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  
  api:
    build: .
    ports:
      - 4001:4001
    environment:
      PORT: 4001
      MONGODB_URI: mongodb+srv://admin:Nguyennhan4720@cluster0.zxoeo.mongodb.net/hip06?retryWrites=true&w=majority
      JWT_SECRET: Rq03AAVqPJQdlniS9E0YGjJijshaisN283GYzSCNCyM63T0QFvO
      EMAIL_NAME: nguyentrongnhan04072000@gmail.com
      EMAIL_APP_PASSWORD: dgxzvalrxjedeulc
      URL_SERVER: http://localhost:4001
      LIMIT_PRODUCTS: 10
      CLOUDINARY_NAME: nhannt
      CLOUDINARY_KEY: 374615425711595
      CLOUDINARY_SECRET: cC4DzsfarNg7-lQmDDSU5Ak6lrQ
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}