export { default as CreateProduct } from './CreateProduct'
export { default as Dashboard } from './Dashboard'
export { default as AdminLayout } from './Layout'
export { default as ManageOrder } from './ManageOrder'
export { default as ManageProduct } from './ManageProduct'
export { default as ManageUser } from './ManageUser'
export { default as UpdateProduct } from './UpdateProduct'